### ISSUE TITLE
Update example for current SDK version (1.8.x)

### ISSUE THREAD

**Issue by oddrationale** [mezoni/dart_and_cpp_classes#1]
I found this example to be very helpful when writing my own Dart VM Native Extension. However, it seems like this version is out-of-date with the current Dart SDK. Can you update it to work with the current version?

It currently does not compile (Ubuntu 14.10 x64):

    $ dart bin/build_cpp_extension.dart 
    Compile...
    cpp_extension.cc: In function ‘_Dart_Handle* cpp_extension_Init(Dart_Handle)’:
    cpp_extension.cc:21:79: error: too few arguments to function ‘_Dart_Handle* Dart_SetNativeResolver(Dart_Handle, Dart_NativeEntryResolver, Dart_NativeEntrySymbol)’
       Dart_Handle result_code = Dart_SetNativeResolver(parent_library, ResolveName);
                                                                                   ^
    In file included from cpp_extension.cc:14:0:
    /home/oddrationale/Applications/dart/editor/dart-sdk/include/dart_api.h:2517:25: note: declared here
     DART_EXPORT Dart_Handle Dart_SetNativeResolver(
                             ^
    cpp_extension.cc: In function ‘void ConnectionPeerRegister(Dart_NativeArguments)’:
    cpp_extension.cc:93:79: error: invalid conversion from ‘void (*)(Dart_WeakPersistentHandle, void*) {aka void (*)(_Dart_WeakPersistentHandle*, void*)}’ to ‘intptr_t {aka long int}’ [-fpermissive]
       Dart_NewWeakPersistentHandle(dh_object, (void*)peer, ConnectionPeerFinalizer);
                                                                                   ^
    cpp_extension.cc:93:79: error: too few arguments to function ‘_Dart_WeakPersistentHandle* Dart_NewWeakPersistentHandle(Dart_Handle, void*, intptr_t, Dart_WeakPersistentHandleFinalizer)’
    In file included from cpp_extension.cc:14:0:
    /home/oddrationale/Applications/dart/editor/dart-sdk/include/dart_api.h:477:39: note: declared here
     DART_EXPORT Dart_WeakPersistentHandle Dart_NewWeakPersistentHandle(
                                           ^
    $

It seems like the `Dart_NewWeakPersistentHandle()` now takes four arguments, but I'm not sure what I'm suppose to put for the extra one.

Thanks for your help!

**Comment by mezoni** [comment]
All bugs was fixed.
More info in https://github.com/mezoni/dart_and_cpp_classes/blob/master/README.md

**Comment by oddrationale** [comment]
Thanks!
